[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'losingkeys/vim-niji'

[[plugins]]
repo = 'evidens/vim-twig'

[[plugins]]
repo = 'groenewege/vim-less'

[[plugins]]
repo = 'h1mesuke/vim-alignta'

[[plugins]]
repo = 'maksimr/vim-jsbeautify'

[[plugins]]
repo = 'mattn/emmet-vim'

[[plugins]]
repo = 'scrooloose/syntastic'

[[plugins]]
repo = 'Shougo/neosnippet'

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/vimproc'
build = 'make'

[[plugins]]
repo = 'vim-scripts/sudo.vim'

[[plugins]]
repo = 'thinca/vim-ref'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'vim-scripts/autodate.vim'

[[plugins]]
repo = 'vim-scripts/YankRing.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'pangloss/vim-javascript'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'vim-jp/vital.vim'

[[plugins]]
repo = 'thinca/vim-themis'

[[plugins]]
repo = 'kchmck/vim-coffee-script'

[[plugins]]
repo = 'einars/js-beautify'

[[plugins]]
repo = 'vim-scripts/JSON.vim'

[[plugins]]
repo = 'vim-perl/vim-perl'

[[plugins]]
repo = 'lambdalisue/gina.vim'

[[plugins]]
repo = 'thinca/vim-vparsec'

[[plugins]]
repo = 'kana/vim-submode'

[[plugins]]
repo = 'kana/vim-smartword'

[[plugins]]
repo = 'roman/golden-ratio'

[[plugins]]
repo = 'ngmy/vim-rubocop'

[[plugins]]
repo = 'cocopon/iceberg.vim'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'Shougo/ddc.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'Shougo/ddc-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'hashivim/vim-terraform'

[[plugins]]
repo = 'stephpy/vim-yaml'
